### ISSUE TITLE
Deploying the mover-ui to RTC CLM 5.0.2 with ifix

### ISSUE THREAD

**Issue by silent-mobius** [jazz-community/rtc-workitem-bulk-mover-ui#12]
I  am trying to move with mover-ui  on RTC version 5.0.2, bulk of tasks, stories and epics to new project.
I have used the installation tutorial accordingly, but i am not seeking any add-on tab certainly i can't find the mover-ui  any where. Can any one assist me on this ?
Thanks in advance.

**Comment by innerjoin** [comment]
Hi @silent-mobius, you have to deploy the Bulk Mover service and the Menu Provider as well. Otherwise, it will not work. If you already did that, search the CCM log for entries containing _com.siemens_ and/or _WorkItemBulkMover_ and let us know why the plugins did not start properly.

**Comment by innerjoin** [comment]
@silent-mobius were you able to resolve the issue?

**Comment by meran** [comment]
Hello,
I did the following actions and encountered the same problems as the previous user but after fixing it I still get some problems.
this is my ccm.log file error:
2018-01-14 14:51:02,558 [              WebContainer : 0]  INFO mapping.internal.GlobalServerRenameProgressService  - CRJAZ2523I Setting the global server rename state to false and the validation state to false.
2018-01-14 14:51:25,442 [              WebContainer : 0]  INFO team.fulltext.service.internal.FullTextServiceImpl  - CRJAZ8190I: The full-text index should point to an absolute directory, but is currently set to 'conf/ccm/indices/workitemindex'. The location of the full-text index will resolve to '/opt/IBM/JazzTeamServer/server/conf/ccm/indices/workitemindex/_UDBp4j0QEeaxXKoO4K5wsA'.
2018-01-14 14:51:25,524 [ccm: Diagnostic com.ibm.team.repository.service.diagnostics.basic.internal.serviceStatusDiagnostic]  WARN com.ibm.team.scm                                    - CRRTC5011W: The versioned content service temp directory should not be put into /tmp as it may get cleaned up by tmpwatch. Please update the value in the Advanced Properties section of the admin web page.
2018-01-14 14:51:26,107 [              WebContainer : 0] ERROR tory.common.transport.services.TeamServiceRegistry  - CRJAZ1143I Failed to register OSGi services for descriptor: ServiceProviderElementDescriptor@ad17b88d, implementationClass="com.siemens.bt.jazz.services.WorkItemBulkMover.WorkItemBulkMoverService", bundle="com.siemens.bt.jazz.services.WorkItemBulkMover", componentId="com.siemens.bt.jazz.services.WorkItemBulkMover", startPolicy=<EARLY>.
java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/siemens/bt/jazz/services/base/BaseService, offset=6
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:264)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:580)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:550)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:481)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass_LockClassName(ClasspathManager.java:460)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:447)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:393)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:650)
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:264)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:580)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:550)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:481)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass_LockClassName(ClasspathManager.java:460)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:447)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:393)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:650)
        at org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:338)
        at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:232)
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1197)
        at com.ibm.team.repository.common.transport.AbstractElementDescriptor.basicLoadClass(AbstractElementDescriptor.java:78)
        at com.ibm.team.repository.common.transport.AbstractElementDescriptor.loadClass(AbstractElementDescriptor.java:515)
        at com.ibm.team.repository.common.transport.internal.registry.ServiceProviderElementDescriptor.getImplementationClass(ServiceProviderElementDescriptor.java:153)
        at com.ibm.team.repository.common.transport.internal.registry.OsgiServicesManager.register(OsgiServicesManager.java:408)
        at com.ibm.team.repository.common.transport.services.TeamServiceRegistry.registerServices(TeamServiceRegistry.java:329)
        at com.ibm.team.repository.common.transport.services.TeamServiceRegistry.initialize(TeamServiceRegistry.java:290)
        at com.ibm.team.repository.common.transport.services.TeamServiceRegistry.start(TeamServiceRegistry.java:371)
        at com.ibm.team.repository.common.transport.services.TeamServiceRegistry.getService(TeamServiceRegistry.java:224)
        at com.ibm.team.repository.service.internal.LogFeedAppender.<init>(LogFeedAppender.java:97)
        at com.ibm.team.repository.service.internal.LogFeedAppender.getInstance(LogFeedAppender.java:105)
        at com.ibm.team.repository.servlet.internal.TeamLogger.init(TeamLogger.java:30)
        at com.ibm.team.repository.servlet.AbstractTeamServerServlet.init(AbstractTeamServerServlet.java:1470)
        at com.ibm.team.repository.servlet.TeamServerServlet.init(TeamServerServlet.java:209)
        at javax.servlet.GenericServlet.init(GenericServlet.java:161)
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.initializeDelegate(ServletManager.java:195)
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:179)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:126)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:76)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
        at org.eclipse.equinox.servletbridge.BridgeServlet.service(BridgeServlet.java:120)
        at com.ibm.team.repository.server.servletbridge.JazzServlet.service(JazzServlet.java:74)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1227)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:776)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:458)
        at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:136)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:97)
        at com.ibm.team.repository.server.servletbridge.BridgeFilter.initialize(BridgeFilter.java:303)
        at com.ibm.team.repository.server.servletbridge.BridgeFilter.doFilter(BridgeFilter.java:196)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:928)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1025)
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3761)
        at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:976)
        at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1662)
        at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:459)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:526)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:312)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:283)
        at com.ibm.ws.ssl.channel.impl.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1048)
        at com.ibm.ws.ssl.channel.impl.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:642)
        at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1784)
        at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
        at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
        at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
        at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
        at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
        at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
        at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
        at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1862)
2018-01-14 14:51:27,474 [              WebContainer : 0]  WARN com.ibm.team.repository.servlet.TeamServerServlet   - CRJAZ1181W Security notice during initialization: Allowing ADMIN user access.  It is recommended that you disable the ADMIN user and create a real user with administrative rights.
2018-01-14 14:51:27,479 [              WebContainer : 0]  WARN com.ibm.team.repository.servlet.TeamServerServlet   - CRJAZ2076I Product Details:
  Change and Configuration Management - Core Libraries, Version 5.0.2 (RTC-I20141031-0926)

I moved all the ini files to the location ( from all 3 plugins ) and then moved the jar files from all 3 plugins to the correct feature/plugin folders in the update-site folder .
I wasn;t able to delete the folder since then all my ccm was unavailable.

please help

**Comment by innerjoin** [comment]
@meran Thank you for reaching out to us. From looking at your provided CCM.log stack trace, this issue might have the same root cause as recently discussed in #1 ... I will look into this teh day after tomorrow

**Comment by meran** [comment]
@innerjoin , thanks for your reply.
just to clarify , in our case the addons menu hasn't even appeared.

thanks again for your help

**Comment by innerjoin** [comment]
@meran 
To reproduce your issue, I went to [Jazz.net](https://jazz.net/downloads/rational-team-concert/releases/5.0.2?p=allDownloads) and downloaded the package _Jazz Team Server and the CCM Application, and Trial licenses for Rational Team Concert_ for RTC 5.0.2. After installing the plug-ins, I went through the server setup and the new Menu entry plus the mover UI were available:

![mover-ui-rtc5 0 2-fresh-install](https://user-images.githubusercontent.com/2387965/35106133-bb1fb47c-fc6d-11e7-9a69-abac7aad6493.png)

If you are not able to see the UI as shown in the screenshot above, please review your deployment. What seems to not work is the service that serves the UI as a data provider, opening the browser console shows the following console error:
https://localhost:9443/ccm/service/com.siemens.bt.jazz.services.WorkItemBulkMover.IWorkItemBulkMoverService/project-areas 
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by innerjoin** [comment]
The above mentioned issue will be tracked [here](https://github.com/jazz-community/rtc-workitem-bulk-mover-service/issues/11)

**Comment by innerjoin** [comment]
@meran Any update from your side?

**Comment by meran** [comment]
Hello @innerjoin ,
I did not have the time to look at it again.

I hope to do it tomorrow.
many thanks

**Comment by innerjoin** [comment]
Closed as there was no response. Please reopen if needed

**Comment by ycon123** [comment]
Hi @innerjoin ,
I'm @meran 's colleague, and I was able to get the Add-On menu to appear.
However, the blue button seems to keep loading, and I can't move forward with the Bulk move operation.
I also see there was a problem on service registration, looking on page: https://server/ccm/admin
![image](https://user-images.githubusercontent.com/14972986/37393077-c08aaff8-2778-11e8-8bdd-12f7f8e69aac.png)

I also checked the browser for errors (chrome):
![image](https://user-images.githubusercontent.com/14972986/37393188-0e98f4b6-2779-11e8-9f72-de2958fdb93c.png)

I would appreciate your help,
Yael

**Comment by innerjoin** [comment]
This is a known issue: https://github.com/jazz-community/rtc-workitem-bulk-mover-service/issues/11

**Comment by ycon123** [comment]
OK I see
Do you have any workaround?

**Comment by innerjoin** [comment]
None that I would be aware of. Maybe @SBI- has one...
